# Generated by Django 3.2.9 on 2022-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_Name', models.CharField(max_length=20)),
                ('tester_Program', models.CharField(max_length=20)),
                ('tester_Gender', models.CharField(max_length=10)),
                ('tester_Age', models.IntegerField(default=0)),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
                ('q5', models.IntegerField(default=0)),
                ('q6', models.IntegerField(default=0)),
                ('q7', models.IntegerField(default=0)),
                ('q8', models.IntegerField(default=0)),
                ('q9', models.IntegerField(default=0)),
                ('q10', models.IntegerField(default=0)),
                ('file_url', models.CharField(max_length=50)),
                ('generate_time', models.CharField(max_length=100)),
            ],
        ),
    ]
