# Generated by Django 4.0.1 on 2022-01-05 12:59

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Paint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testersdata',
            name='start_time',
            field=models.DateTimeField(default=timezone.make_aware(datetime.fromtimestamp(0))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testersdata',
            name='tester_Role',
            field=models.CharField(default='undergraduate', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testersdata',
            name='generate_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testersdata',
            name='tester_Program',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
