# Generated by Django 4.0.1 on 2022-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paint', '0002_testersdata_start_time_testersdata_tester_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testersdata',
            name='tester_No',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
