from django.db import models


# Create your models here.
class testersData(models.Model):
    tester_Name = models.CharField(max_length=20)
    tester_Role = models.CharField(max_length=20)
    tester_No = models.CharField(max_length=20)
    tester_Program = models.CharField(max_length=20, blank=True)
    tester_Gender = models.CharField(max_length=10)
    tester_Age = models.IntegerField(default=0)
    q1 = models.IntegerField(default=0)
    q2 = models.IntegerField(default=0)
    q3 = models.IntegerField(default=0)
    q4 = models.IntegerField(default=0)
    q5 = models.IntegerField(default=0)
    q6 = models.IntegerField(default=0)
    q7 = models.IntegerField(default=0)
    q8 = models.IntegerField(default=0)
    q9 = models.IntegerField(default=0)
    q10 = models.IntegerField(default=0)
    square_color = models.CharField(max_length=10)
    square_feeling1 = models.IntegerField()
    square_feeling2 = models.IntegerField()
    square_feeling3 = models.IntegerField()
    triangle_color = models.CharField(max_length=10)
    triangle_feeling1 = models.IntegerField()
    triangle_feeling2 = models.IntegerField()
    triangle_feeling3 = models.IntegerField()
    circle_color = models.CharField(max_length=10)
    circle_feeling1 = models.IntegerField()
    circle_feeling2 = models.IntegerField()
    circle_feeling3 = models.IntegerField()
    halfcircle_color = models.CharField(max_length=10)
    halfcircle_feeling1 = models.IntegerField()
    halfcircle_feeling2 = models.IntegerField()
    halfcircle_feeling3 = models.IntegerField()
    blindtest = models.CharField(max_length=20)
    file_url = models.CharField(max_length=50)
    start_time = models.DateTimeField()
    generate_time = models.DateTimeField(auto_now_add=True)
